import { useState } from 'react'
import './records.css'

type Note = { id:string; title:string; date:string; feeling:string; pregnancy:string; visit:string; injuries:string; medication:string; shared:boolean }
type IconName = 'back'|'exit'|'home'|'chat'|'wallet'|'settings'|'lock'|'people'|'check'
const icons:Record<IconName,React.ReactNode> = {
  back:<path d="m15 18-6-6 6-6"/>, exit:<><path d="M10 5H5v14h5"/><path d="m14 8 4 4-4 4M8 12h10"/></>, home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/></>, chat:<path d="M20 11.5a8 8 0 0 1-9.1 7.9L5 21l1.6-4A8 8 0 1 1 20 11.5Z"/>, wallet:<><path d="M3 6h15a2 2 0 0 1 2 2v11H5a2 2 0 0 1-2-2V6Z"/><path d="M15 11h6v5h-6a2 2 0 0 1 0-5Z"/></>, settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>, lock:<><rect x="6" y="10" width="12" height="10" rx="2"/><path d="M9 10V7a3 3 0 0 1 6 0v3"/></>, people:<><circle cx="9" cy="8" r="3"/><path d="M3 19a6 6 0 0 1 12 0M17 8h4M19 6v4"/></>, check:<path d="m5 12 4 4L19 6"/>
}
function Icon({name,size=22}:{name:IconName;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg>}
const initial:Note[]=[{id:'checkup',title:'Check-up notes',date:'20 Sep 2026',feeling:'Tired but hopeful',pregnancy:'2nd trimester',visit:'15 Sep 2026',injuries:'Headaches, bruising on left arm',medication:'Paracetamol',shared:false},{id:'clinic',title:'Clinic visit',date:'15 Sep 2026',feeling:'Recovering',pregnancy:'Prefer not to say',visit:'15 Sep 2026',injuries:'',medication:'',shared:true}]
function loadNotes(){try{const value=localStorage.getItem('health-records');return value?JSON.parse(value) as Note[]:initial}catch{return initial}}
function saveNotes(notes:Note[]){localStorage.setItem('health-records',JSON.stringify(notes))}
const go=(path:string)=>window.location.assign(path)
function Header({title}:{title:string}){return <header className="records-header"><button onClick={()=>history.back()} aria-label="Go back"><Icon name="back" size={18}/></button><h1>{title}</h1><button className="records-exit" onClick={()=>window.location.replace('/')}><Icon name="exit" size={17}/>Exit</button></header>}
function Nav(){return <nav className="records-nav"><a href="/app"><Icon name="home"/><span>Home</span></a><a href="/app/messages"><Icon name="chat"/><span>Messages</span></a><a href="/app/wallet"><Icon name="wallet"/><span>Wallet</span></a><a className="active" href="/app/settings"><Icon name="settings"/><span>Settings</span></a></nav>}
function Screen({title,children,className=''}:React.PropsWithChildren<{title:string;className?:string}>){return <div className={`records-screen ${className}`}><Header title={title}/>{children}<Nav/></div>}
function RecordsHome(){const [notes]=useState(loadNotes);return <Screen title="My records"><p className="records-intro">These notes stay on this phone. Only you can see them unless you choose to share.</p><main className="record-list">{notes.map(note=><button key={note.id} onClick={()=>go(`/app/records/${note.id}`)}><span><small>{note.date}</small>{note.shared?<b className="shared"><Icon name="people" size={14}/>Shared with Grace</b>:<b><Icon name="lock" size={14}/>Private</b>}</span><strong>{note.title}</strong></button>)}</main><button className="records-primary" onClick={()=>go('/app/records/new')}>Add a note</button></Screen>}
const today=()=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'Africa/Nairobi'}).format(new Date())
function NewNote(){const [feeling,setFeeling]=useState(''),[pregnancy,setPregnancy]=useState(''),[visit,setVisit]=useState(''),[injuries,setInjuries]=useState(''),[medication,setMedication]=useState('');const submit=()=>{const notes=loadNotes();const note:Note={id:`note-${Date.now()}`,title:visit?'Clinic visit':'Health note',date:today(),feeling,pregnancy,visit:visit?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${visit}T12:00:00`)):'',injuries,medication,shared:false};saveNotes([note,...notes]);go(`/app/records/${note.id}`)};return <Screen title="New health note" className="record-form"><p>Only fill in what you want to. All fields are optional.</p><label>How are you feeling?<input value={feeling} onChange={e=>setFeeling(e.target.value)} placeholder="Describe your general mood or status"/></label><fieldset><legend>Pregnancy</legend>{['Not pregnant','1st trimester','2nd trimester','3rd trimester','Prefer not to say'].map(value=><button type="button" className={pregnancy===value?'selected':''} onClick={()=>setPregnancy(value)} key={value}>{value}</button>)}</fieldset><label>Last clinic visit<input type="date" value={visit} onChange={e=>setVisit(e.target.value)}/></label><label>Injuries or symptoms<textarea value={injuries} onChange={e=>setInjuries(e.target.value)} placeholder="Mention physical discomfort, pain or recent trauma..."/></label><label>Medication<input value={medication} onChange={e=>setMedication(e.target.value)} placeholder="e.g. Paracetamol, dosage"/></label><button className="records-primary" onClick={submit}>Save note</button><small className="local-only">Saved only on this phone.</small></Screen>}
function findNote(){const id=window.location.pathname.split('/')[3];return loadNotes().find(note=>note.id===id)??loadNotes()[0]}
function Detail(){const note=findNote();const [dialog,setDialog]=useState(false);const stop=()=>{const notes=loadNotes().map(item=>item.id===note.id?{...item,shared:false}:item);saveNotes(notes);setDialog(false);window.location.reload()};return <Screen title="Note details"><main className="note-detail"><section><span><strong>Saved Record</strong><button>Edit</button></span>{[['How are you feeling?',note.feeling],['Pregnancy',note.pregnancy],['Last clinic visit',note.visit],['Injuries or symptoms',note.injuries],['Medication',note.medication]].filter(([,value])=>value).map(([label,value])=><dl key={label}><dt>{label}</dt><dd>{value}</dd></dl>)}</section><h2>Sharing</h2>{note.shared&&<section className="sharing-card"><span className="grace-avatar">G</span><p>Grace (Counselor)<small>Verified by FIDA Kenya · {note.date}</small></p><button onClick={()=>setDialog(true)}>Stop sharing</button></section>}<button className="records-primary" onClick={()=>go(`/app/records/${note.id}/share`)}>{note.shared?'Share with another counselor':'Share with a counselor'}</button></main>{dialog&&<><button className="record-backdrop" onClick={()=>setDialog(false)} aria-label="Close confirmation"/><section className="stop-sheet" role="dialog" aria-modal="true"><i/><h2>Stop sharing with Grace?</h2><p>Grace won’t see this note or any changes from now on. If she has already opened it, she may still have what she saw.</p><button onClick={stop}>Stop sharing</button><button onClick={()=>setDialog(false)}>Keep sharing</button></section></>}</Screen>}
function Share(){const note=findNote();const [reason,setReason]=useState('For my care'),[consent,setConsent]=useState(false);const share=()=>{const notes=loadNotes().map(item=>item.id===note.id?{...item,shared:true}:item);saveNotes(notes);go(`/app/records/${note.id}`)};return <Screen title="Share this note"><main className="share-note"><h2><b>1</b>Choose a counselor</h2><button className="counselor-choice"><span>G</span><p>Counselor Grace<small>△ VERIFIED BY FIDA KENYA</small></p><i>●</i></button><h2><b>2</b>They will see:</h2><ul>{[['How are you feeling',note.feeling],['Pregnancy',note.pregnancy],['Last clinic visit',note.visit],['Injuries',note.injuries],['Medication',note.medication]].filter(([,value])=>value).map(([label,value])=><li key={label}>{label}: {value}</li>)}</ul><label>Why are you sharing?</label><div className="share-reasons">{['For my care','For a referral'].map(value=><button className={reason===value?'selected':''} onClick={()=>setReason(value)} key={value}>{value}</button>)}</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to share this note with Grace.</label><button className="records-primary" disabled={!consent} onClick={share}>Share note</button></main></Screen>}
export default function Records(){const path=window.location.pathname;if(path.endsWith('/new'))return <NewNote/>;if(path.endsWith('/share'))return <Share/>;if(path==='/app/records')return <RecordsHome/>;return <Detail/>}
