import { useEffect, useRef, useState } from 'react'
import { conversationsOf } from '../messaging/chat'
import { ChatNotice, PinUnlock } from '../messaging/ChatParts'
import { statusLabel as deliveryLabel, timeLabel } from '../messaging/labels'
import { useMessenger } from '../messaging/useMessenger'
import { accountVault } from '../security/vault'
import './counselor.css'

type Doc={id:string;label:string;name:string;size:string;status:'sent'|'sending'|'failed';progress?:number;required?:boolean}
const go=(path:string)=>window.location.assign(path)
function Exit(){return <button className="co-exit" onClick={()=>window.location.replace('/')}><span>↪</span>Exit</button>}
function Header({title,back=false}:{title:string;back?:boolean}){return <header className="co-header">{back&&<button className="co-back" onClick={()=>history.back()} aria-label="Go back">‹</button>}<h1>{title}</h1><Exit/></header>}
function Screen({title,back=false,children,className=''}:React.PropsWithChildren<{title:string;back?:boolean;className?:string}>){return <main className={`co-screen ${className}`}><Header title={title} back={back}/>{children}</main>}

function Invite(){const [code,setCode]=useState('');const valid=/^[A-Za-z0-9-]{6,}$/.test(code);return <Screen title="Welcome" className="co-invite"><section><h2>Join Resilience as a counselor</h2><p>Your organisation sends you a one-time invite code. Enter it to get started.</p><label>Invite code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="e.g. ORG-4F7K-92Q" autoComplete="one-time-code"/></label><small>Works once and expires after 7 days.</small><aside><span>◉</span>Survivors never see your real name or phone number. You’ll choose a display name next.</aside></section><button className="co-primary" disabled={!valid} onClick={()=>{sessionStorage.setItem('counselor-invite',code);go('/counselor/profile')}}>Continue</button><button className="co-text" onClick={()=>go('/counselor/sign-in')}>I already have a counselor account</button></Screen>}

// A counselor's key is the one her organisation put on its signed list. She brings it to this phone
// with her 12 backup words, and it is stored in the same PIN-locked vault survivors use.
function SignIn(){const [words,setWords]=useState(''),[name,setName]=useState(''),[pin,setPin]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const ready=words.trim().split(/\s+/).length===12&&name.trim().length>0&&/^\d{4}$/.test(pin);const submit=async()=>{setBusy(true);setError('');try{await accountVault.restore(words.trim().toLowerCase().split(/\s+/).join(' '),pin,name.trim());sessionStorage.setItem('counselor-name',name.trim());go('/counselor/inbox')}catch{setError('Those backup words didn’t work. Check the spelling and the order.');setBusy(false)}};return <Screen title="Sign in" back className="co-profile co-sign-in"><p>Enter the 12 backup words for the key your organisation verified. They never leave this phone.</p><label>Backup words<textarea value={words} onChange={e=>setWords(e.target.value)} autoComplete="off" autoCapitalize="none" spellCheck={false} rows={3} placeholder="word1 word2 … word12"/></label><label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Counselor Grace"/><small>Survivors see the name on your verified profile, not this one.</small></label><label>Choose a 4-digit PIN<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" type="password" autoComplete="new-password"/></label>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" disabled={!ready||busy} onClick={()=>void submit()}>{busy?'Signing in securely…':'Sign in'}</button></Screen>}

const helpOptions=['Trauma support','Legal aid','Health','Shelter','Family and children'],languageOptions=['English','Kiswahili','Dholuo','Somali']
function Profile(){const [name,setName]=useState(sessionStorage.getItem('counselor-name')||'Counselor Grace'),[help,setHelp]=useState<string[]>(['Trauma support','Legal aid']),[languages,setLanguages]=useState<string[]>(['English','Kiswahili']);const toggle=(list:string[],value:string,set:(values:string[])=>void)=>set(list.includes(value)?list.filter(item=>item!==value):[...list,value]);const next=()=>{sessionStorage.setItem('counselor-name',name.trim());sessionStorage.setItem('counselor-help',JSON.stringify(help));sessionStorage.setItem('counselor-languages',JSON.stringify(languages));go('/counselor/credentials')};return <Screen title="Your profile" back className="co-profile"><label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40}/><small>Use a first name or a professional name, not your full name.</small></label><fieldset><legend>What you help with</legend><div>{helpOptions.map(value=><button type="button" className={help.includes(value)?'selected':''} onClick={()=>toggle(help,value,setHelp)} key={value}>{value}</button>)}</div></fieldset><fieldset><legend>Languages</legend><div>{languageOptions.map(value=><button type="button" className={languages.includes(value)?'selected':''} onClick={()=>toggle(languages,value,setLanguages)} key={value}>{value}</button>)}</div></fieldset><section className="co-preview"><small>HOW SURVIVORS WILL SEE YOU</small><strong>{name||'Your display name'}</strong><span>◷ Not verified yet</span></section><button className="co-primary" disabled={!name.trim()||!help.length||!languages.length} onClick={next}>Continue</button></Screen>}

const defaults:Doc[]=[{id:'certificate',label:'Counselling licence or certificate',name:'certificate.pdf',size:'1.2 MB',status:'sent',required:true},{id:'letter',label:'Letter from your organisation',name:'letter.pdf',size:'380 KB',status:'sending',progress:60,required:true},{id:'supporting',label:'Other supporting document (optional)',name:'registration.jpg',size:'2.4 MB',status:'failed'}]
function Credentials(){const [docs,setDocs]=useState<Doc[]>(defaults),input=useRef<HTMLInputElement>(null);useEffect(()=>{const timer=window.setTimeout(()=>setDocs(current=>current.map(doc=>doc.status==='sending'?{...doc,status:'sent',progress:100}:doc)),1600);return()=>window.clearTimeout(timer)},[]);const add=(file?:File)=>{if(!file)return;setDocs(current=>[...current,{id:`doc-${Date.now()}`,label:'Other supporting document (optional)',name:file.name,size:`${(file.size/1024/1024).toFixed(1)} MB`,status:'sending',progress:25}]);window.setTimeout(()=>setDocs(current=>current.map(doc=>doc.name===file.name?{...doc,status:'sent',progress:100}:doc)),1300)};const retry=(id:string)=>{setDocs(current=>current.map(doc=>doc.id===id?{...doc,status:'sending',progress:35}:doc));window.setTimeout(()=>setDocs(current=>current.map(doc=>doc.id===id?{...doc,status:'sent',progress:100}:doc)),1200)};const ready=docs.filter(doc=>doc.required).every(doc=>doc.status==='sent');return <Screen title="Your credentials" back className="co-credentials"><p>Partner organisation A checks your documents before you can talk to anyone.</p><div className="co-docs">{docs.map(doc=><section key={doc.id}><label>{doc.label}</label><button className={doc.status} onClick={()=>doc.status==='failed'&&retry(doc.id)}><span>▤</span><span><strong>{doc.name} · {doc.size}</strong><small>{doc.status==='sent'?'✓ Sent to Partner organisation A':doc.status==='failed'?"! Couldn’t send. Tap to retry":`Sending… ${doc.progress||25}%`}</small>{doc.status==='sending'&&<i style={{width:`${doc.progress||25}%`}}/>}</span></button></section>)}</div><input ref={input} type="file" hidden accept=".pdf,.jpg,.jpeg,.png" onChange={event=>add(event.target.files?.[0])}/><button className="co-add" onClick={()=>input.current?.click()}>↥ Add a document</button><aside>▢ <span>Selected files stay on this device in this prototype. A production version must encrypt them directly for the reviewing organisation.</span></aside><button className="co-primary" disabled={!ready} onClick={()=>go('/counselor/review')}>Submit for review</button></Screen>}

function Review(){return <Screen title="Verification" className="co-status"><section><span className="co-status-icon pending">◷</span><h2>Your documents are with Partner organisation A</h2><p>Most reviews take 1 to 3 working days. We’ll let you know with a discreet notification.</p><ul><li className="done">✓ <span>Documents sent</span></li><li className="waiting">◷ <span>Organisation review: in progress</span></li><li>♢ <span>Verified badge added to your profile</span></li></ul></section><button className="co-secondary" onClick={()=>go('/counselor/profile')}>Edit my profile</button><button className="co-prototype" onClick={()=>go('/counselor/more-information')}>Preview information-request state</button></Screen>}
function MoreInfo(){return <Screen title="Verification" className="co-status"><section><span className="co-status-icon attention">!</span><h2>Partner organisation A needs one more thing</h2><article><small>MESSAGE FROM YOUR ORGANISATION</small><p>Please upload a clearer copy of your certificate. We can’t read the expiry date.</p></article></section><button className="co-primary" onClick={()=>go('/counselor/credentials')}>Upload again</button></Screen>}
function Verified(){const name=sessionStorage.getItem('counselor-name')||'Counselor Grace';return <Screen title="Verification" className="co-status"><section><span className="co-status-icon verified">✓</span><h2>You’re verified</h2><p>Partner organisation A confirmed your credentials. Survivors now see this on your profile:</p><article className="verified-card"><strong>{name}</strong><span>♢ Verified by Partner organisation A</span><small>Verification expires March 2027. Your organisation can renew or remove it.</small></article><aside>◉ <span>Resilience never stored your documents. Only the verification appears on your profile.</span></aside></section><button className="co-primary" onClick={()=>go('/counselor/inbox')}>Go to my inbox</button></Screen>}

type InboxTab='requests'|'active'
function CounselorNav({active='inbox'}:{active?:'inbox'|'wallet'|'settings'}){return <nav className="co-nav" aria-label="Counselor navigation"><a className={active==='inbox'?'active':''} href="/counselor/inbox"><span>▱</span>Inbox</a><a className={active==='wallet'?'active':''} href="/counselor/wallet"><span>▣</span>Wallet</a><a className={active==='settings'?'active':''} href="/counselor/settings"><span>⚙</span>Settings</a></nav>}
function Inbox(){const [available,setAvailable]=useState(true),[tab,setTab]=useState<InboxTab>('requests');const chat=useMessenger('counselor',false);const all=chat.state.kind==='ready'?conversationsOf(chat.messages):[];const fresh=all.filter(item=>!item.repliedByMe),active=all.filter(item=>item.repliedByMe);const shown=tab==='requests'?fresh:active;
let body:React.ReactNode;
if(chat.state.kind==='no-account')body=<ChatNotice action={{label:'Sign in',run:()=>go('/counselor/sign-in')}}>Sign in with your backup words to see messages from survivors.</ChatNotice>;
else if(chat.state.kind==='locked')body=<PinUnlock title={`Welcome back, ${chat.state.nickname}`} text="Enter your PIN to open your inbox." unlock={chat.unlock}/>;
else if(chat.state.kind==='error')body=<ChatNotice action={{label:'Try again',run:()=>void chat.retry()}}>{chat.state.message}</ChatNotice>;
else if(chat.state.kind!=='ready')body=<p className="chat-empty">Connecting securely…</p>;
else body=<section className="co-chat-list">{tab==='active'&&<small className="co-list-label">ACTIVE</small>}{shown.map(item=><button className="co-chat-row" onClick={()=>go(`/counselor/chat/${item.peer}`)} key={item.conversationId}><span className="co-avatar">{item.peerName.charAt(0).toUpperCase()}</span><span><strong>{item.peerName} {!item.peerIsGuest&&!item.repliedByMe&&<small>New</small>}</strong><span>{item.last.fromMe?'You: ':''}{item.last.text}</span></span><time>{timeLabel(item.last.createdAt)}</time></button>)}{shown.length===0&&<p className="chat-empty">{tab==='requests'?'No new requests. New conversations from survivors appear here.':'No active conversations yet.'}</p>}</section>;
return <main className="co-screen co-work"><Header title="Inbox"/><section className="co-availability"><span><strong>You’re {available?'available':'unavailable'}</strong><small>{available?'Survivors can send you new requests.':'New requests are paused.'}</small></span><button role="switch" aria-checked={available} className={available?'on':''} onClick={()=>setAvailable(value=>!value)}><i/></button></section><div className="co-tabs" role="tablist"><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}>New requests · {fresh.length}</button><button className={tab==='active'?'active':''} onClick={()=>setTab('active')}>Active · {active.length}</button></div>{body}<aside className="co-privacy-note">◉ <span>People appear by nickname only. You never see a phone number, location or account ID.</span></aside><CounselorNav/></main>}

// A real conversation with one survivor, addressed by her public key.
function LiveChat({peer}:{peer:string}){const chat=useMessenger('counselor',false);const [message,setMessage]=useState(''),[error,setError]=useState('');const thread=chat.messages.filter(item=>item.peer===peer);const name=thread.find(item=>!item.fromMe)?.peerName??'Survivor';const guest=thread.some(item=>item.peerIsGuest);const send=async()=>{if(!message.trim()||!chat.messenger)return;const text=message;setMessage('');setError('');try{await chat.messenger.send(peer,name,text)}catch{setMessage(text);setError('That message couldn’t be sent. Try again.')}};
let body:React.ReactNode;
if(chat.state.kind==='no-account')body=<ChatNotice action={{label:'Sign in',run:()=>go('/counselor/sign-in')}}>Sign in with your backup words first.</ChatNotice>;
else if(chat.state.kind==='locked')body=<PinUnlock title={`Welcome back, ${chat.state.nickname}`} text="Enter your PIN to open this conversation." unlock={chat.unlock}/>;
else if(chat.state.kind==='error')body=<ChatNotice action={{label:'Try again',run:()=>void chat.retry()}}>{chat.state.message}</ChatNotice>;
else if(chat.state.kind!=='ready')body=<p className="chat-empty">Connecting securely…</p>;
else body=<section className="co-thread">{thread.length===0&&<p className="chat-empty">No messages in this conversation on this phone.</p>}{thread.map(item=><p className={item.fromMe?'sent':'received'} key={item.id}>{item.text}{item.fromMe&&<small>{deliveryLabel(item)}</small>}</p>)}</section>;
const ready=chat.state.kind==='ready'&&thread.length>0;
return <main className="co-screen co-work-chat"><Header title={name} back/>{ready&&<span className="co-guest-tag">{guest?'Guest':'Account'}</span>}{ready&&guest&&<aside className="co-chat-warning">ⓘ <span>Guest: this conversation clears when she leaves. Don’t ask for her name, phone number or location.</span></aside>}{body}{ready&&<div className="co-tools"><button>▣ Share a resource</button><button>↗ Refer</button><button>♧ Emergency numbers</button><button disabled={guest} onClick={()=>go('/counselor/support-request')}>▢ Request support</button></div>}{ready&&guest&&<small className="co-tool-hint">Request support is available when she has an account.</small>}{error&&<small className="co-error" role="alert">{error}</small>}{ready&&<form className="co-composer" onSubmit={event=>{event.preventDefault();void send()}}><input aria-label="Message" value={message} maxLength={2000} onChange={event=>setMessage(event.target.value)} placeholder="Write a message…"/><button disabled={!message.trim()} aria-label="Send message">➤</button></form>}</main>}

function WorkChat({person}:{person:string}){const guest=person!=='Amani';const [message,setMessage]=useState('');useEffect(()=>{if(!guest)return;const timer=window.setTimeout(()=>go('/counselor/chat-ended'),8000);return()=>window.clearTimeout(timer)},[guest]);return <main className="co-screen co-work-chat"><Header title={person} back/><span className="co-guest-tag">{guest?'Guest':'Account'}</span>{guest&&<aside className="co-chat-warning">ⓘ <span>Guest: this conversation clears when she leaves. Don’t ask for her name, phone number or location.</span></aside>}<section className="co-thread"><p className="received">{person==='Sky 42'?'I need someone to talk to':'Things at home are getting worse. I don’t know where to go.'}</p><p className="sent">I’m here, {person}. Take your time. I’m listening.<small>Sent</small></p><p className="received">Things at home are getting worse.<br/>I don’t know where to go.</p><p className="sent">Thank you for telling me. Would it help to look at safe places near you together?<small>Sending</small></p></section><div className="co-tools"><button>▣ Share a resource</button><button>↗ Refer</button><button>♧ Emergency numbers</button><button disabled={guest} onClick={()=>go('/counselor/support-request')}>▢ Request support</button></div>{guest&&<small className="co-tool-hint">Request support is available when she has an account.</small>}<form className="co-composer" onSubmit={event=>{event.preventDefault();setMessage('')}}><input aria-label="Message" value={message} onChange={event=>setMessage(event.target.value)} placeholder="Write a message…"/><button disabled={!message.trim()} aria-label="Send message">➤</button></form></main>}

function ChatEnded(){return <Screen title="Sky 42" back className="co-status co-ended"><section><span className="co-status-icon">▣</span><h2>Sky 42 has left</h2><p>Guest conversations end when she leaves Resilience. You can’t message her again, and she can’t see this conversation any more.</p></section><button className="co-primary" onClick={()=>go('/counselor/inbox')}>Back to inbox</button></Screen>}

const amounts=['KES 1,000','KES 2,500','KES 5,000','Other amount'],reasons=['Transport to safety','Medical costs','Food and essentials','Legal fees','Other']
function SupportRequest(){const [amount,setAmount]=useState('KES 2,500'),[reason,setReason]=useState('Transport to safety'),[note,setNote]=useState('');return <Screen title="Request support" back className="co-request"><strong>For Amani</strong><fieldset><legend>Amount</legend><div>{amounts.map(value=><button className={amount===value?'selected':''} onClick={()=>setAmount(value)} key={value}>{value}</button>)}</div></fieldset>{amount==='Other amount'&&<label className="co-custom-amount">Custom amount<input inputMode="numeric" placeholder="KES 0"/></label>}<small>Paid from Partner organisation A’s fund.</small><fieldset><legend>Reason</legend><div>{reasons.map(value=><button className={reason===value?'selected':''} onClick={()=>setReason(value)} key={value}>{value}</button>)}</div></fieldset><label>Note for your organisation (optional)<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="e.g. Needs fare to reach a shelter tonight"/></label><small>Don’t include her real name, phone number or location.</small><aside>◉ <span>Partner organisation A sees the amount, the reason and your name. They don’t see who Amani is.</span></aside><button className="co-primary" onClick={()=>go('/counselor/support-request/sent')}>Send request</button></Screen>}
function SupportSent(){return <Screen title="Request support" className="co-status co-request-sent"><section><span className="co-status-icon verified">✓</span><h2>Request sent to Partner organisation A</h2><p>If approved, KES 2,500 arrives in Amani’s wallet as an Emergency Grant. She chooses when it’s safe to withdraw.</p><strong className="co-pending">● Pending approval</strong></section><button className="co-primary" onClick={()=>go('/counselor/chat/amani')}>Back to chat</button></Screen>}

const counselorPayments=[{icon:'✓',title:'Monthly payment',meta:'Partner organisation A · Received',amount:'+KES 7,800',state:'received'},{icon:'◷',title:'Session support',meta:'Partner organisation A · Pending',amount:'+KES 3,100',state:'pending'},{icon:'↥',title:'Withdrawal to M-Pesa',meta:'Completed',amount:'−KES 3,900',state:'complete'},{icon:'!',title:'Payment request',meta:'Expired',amount:'KES 3,100',state:'expired'}]
function CounselorWallet(){const [copied,setCopied]=useState(false);const copy=async()=>{try{await navigator.clipboard.writeText('grace@pay.example')}catch{/* Clipboard can be unavailable outside HTTPS. */}setCopied(true);window.setTimeout(()=>setCopied(false),1600)};return <main className="co-screen co-work co-wallet"><Header title="Wallet"/><p className="co-test-mode">TEST MODE: NO REAL MONEY</p><section className="co-balance"><small>Balance</small><h2>KES 10,900</h2><p>Paid by your organisation. Withdraw to M-Pesa any time.</p><div><button onClick={()=>go('/app/wallet/withdraw')}>Withdraw</button><button onClick={copy}>Receive</button></div></section><section className="co-address"><strong>Your payment address</strong><p><span>grace@pay.example</span><button onClick={copy}>{copied?'Copied':'Copy'}</button></p><small>Share this with your organisation so they can pay you.</small></section><small className="co-list-label">RECENT PAYMENTS</small><section className="co-payments">{counselorPayments.map(payment=><article key={payment.title}><span className={payment.state}>{payment.icon}</span><span><strong>{payment.title}</strong><small>{payment.meta}</small></span><strong>{payment.amount}</strong></article>)}</section><CounselorNav active="wallet"/></main>}

function CounselorSettings(){const initial=sessionStorage.getItem('counselor-available')!=='false';const [available,setAvailable]=useState(initial);const updateAvailability=()=>setAvailable(value=>{sessionStorage.setItem('counselor-available',String(!value));return !value});return <main className="co-screen co-work co-settings"><Header title="Settings"/><small className="co-list-label">AVAILABILITY</small><section><div><span>Available for new requests</span><button role="switch" aria-checked={available} className={`co-settings-switch ${available?'on':''}`} onClick={updateAvailability}><i/></button></div><button><span>Working hours</span><small>Weekdays 9:00–17:00</small></button></section><small className="co-list-label">PROFILE</small><section><button onClick={()=>go('/counselor/profile')}><span>Display name</span><small>{sessionStorage.getItem('counselor-name')||'Counselor Grace'}</small></button><button onClick={()=>go('/counselor/profile')}><span>Focus areas and languages</span><small>4 selected</small></button></section><small className="co-list-label">VERIFICATION</small><section className="co-verification"><strong>♢ Verified by Partner organisation A</strong><small>Expires March 2027. Renewed by your organisation.</small></section><small className="co-list-label">SAFETY</small><section><button onClick={()=>go('/app/settings/notifications')}><span>Notifications</span><small>Discreet</small></button><button onClick={()=>go('/app/settings/timer')}><span>Auto-exit timer</span><small>2 minutes</small></button><button onClick={()=>go('/app/settings/pin')}><span>Change PIN</span></button></section><button className="co-sign-out" onClick={()=>window.location.replace('/')}>Sign out</button><CounselorNav active="settings"/></main>}

export default function CounselorOnboarding(){const path=window.location.pathname;if(path.endsWith('/profile'))return <Profile/>;if(path.endsWith('/credentials'))return <Credentials/>;if(path.endsWith('/review'))return <Review/>;if(path.endsWith('/more-information'))return <MoreInfo/>;if(path.endsWith('/verified'))return <Verified/>;if(path.endsWith('/inbox'))return <Inbox/>;if(path.endsWith('/wallet'))return <CounselorWallet/>;if(path.endsWith('/settings'))return <CounselorSettings/>;if(path.endsWith('/chat-ended'))return <ChatEnded/>;if(path.endsWith('/support-request/sent'))return <SupportSent/>;if(path.endsWith('/support-request'))return <SupportRequest/>;if(path.endsWith('/sign-in'))return <SignIn/>;if(path.includes('/chat/')){const slug=path.split('/').pop()??'';if(/^[0-9a-f]{64}$/.test(slug))return <LiveChat peer={slug} key={slug}/>;const person=slug==='sky-42'?'Sky 42':slug==='amani'?'Amani':slug==='hope'?'Hope':'River';return <WorkChat person={person}/>}return <Invite/>}
