import { useEffect, useState } from 'react'
import type { CounselorEnrollment, Disbursement } from '../api/types'
import { conversationsOf } from '../messaging/chat'
import { ChatNotice, PinUnlock } from '../messaging/ChatParts'
import { statusLabel as deliveryLabel, timeLabel } from '../messaging/labels'
import { useMessenger } from '../messaging/useMessenger'
import { backupDownloadText, backupPhrase } from '../security/backupExport'
import { accountVault } from '../security/vault'
import {
  counselorApi,
  encryptCredential,
  readEnrollment,
  readProfileDraft,
  recoverEnrollment,
  saveEnrollment,
  saveProfileDraft,
  signProfile,
} from './enrollment'
import './counselor.css'

type CredentialSlot='certificate'|'letter'|'supporting'
type SelectedCredential={slot:CredentialSlot;label:string;file:File;required:boolean}
const go=(path:string)=>window.location.assign(path)
function Exit(){return <button className="co-exit" onClick={()=>{accountVault.lock();window.location.replace('/')}}><span>↪</span>Exit</button>}
function Header({title,back=false}:{title:string;back?:boolean}){return <header className="co-header">{back&&<button className="co-back" onClick={()=>history.back()} aria-label="Go back">‹</button>}<h1>{title}</h1><Exit/></header>}
function Screen({title,back=false,children,className=''}:React.PropsWithChildren<{title:string;back?:boolean;className?:string}>){return <main className={`co-screen ${className}`}><Header title={title} back={back}/>{children}</main>}

function Invite(){const [code,setCode]=useState('');const valid=/^[A-Za-z0-9-]{6,}$/.test(code);return <Screen title="Welcome" className="co-invite"><section><h2>Join Resilience as a counselor</h2><p>Your organisation sends you a one-time invite code. Enter it to get started.</p><label>Invite code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="e.g. ORG-4F7K-92Q" autoComplete="one-time-code"/></label><small>Works once and expires after 7 days.</small><aside><span>◉</span>Survivors never see your real name or phone number. You’ll choose a display name next.</aside></section><button className="co-primary" disabled={!valid} onClick={()=>{sessionStorage.setItem('counselor-invite',code);go('/counselor/profile')}}>Continue</button><button className="co-text" onClick={()=>go('/counselor/sign-in')}>I already have a counselor account</button></Screen>}

// A counselor's key is the one her organisation put on its signed list. She brings it to this phone
// with her 12 backup words, and it is stored in the same PIN-locked vault survivors use.
function SignIn(){const [words,setWords]=useState(''),[name,setName]=useState(''),[pin,setPin]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const ready=words.trim().split(/\s+/).length===12&&name.trim().length>0&&/^\d{4}$/.test(pin);const submit=async()=>{setBusy(true);setError('');try{await accountVault.restore(words.trim().toLowerCase().split(/\s+/).join(' '),pin,name.trim());sessionStorage.setItem('counselor-name',name.trim());go('/counselor/inbox')}catch{setError('Those backup words didn’t work. Check the spelling and the order.');setBusy(false)}};return <Screen title="Sign in" back className="co-profile co-sign-in"><p>Enter the 12 backup words for the key your organisation verified. They never leave this phone.</p><label>Backup words<textarea value={words} onChange={e=>setWords(e.target.value)} autoComplete="off" autoCapitalize="none" spellCheck={false} rows={3} placeholder="word1 word2 … word12"/></label><label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Counselor Grace"/><small>Survivors see the name on your verified profile, not this one.</small></label><label>Choose a 4-digit PIN<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" type="password" autoComplete="new-password"/></label>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" disabled={!ready||busy} onClick={()=>void submit()}>{busy?'Signing in securely…':'Sign in'}</button></Screen>}

const helpOptions=['Trauma support','Legal aid','Health','Shelter','Family and children'],languageOptions=['English','Kiswahili','Dholuo','Somali']
function Profile(){const stored=readProfileDraft(),enrollment=readEnrollment();const [name,setName]=useState(stored?.name||enrollment?.profile.name||''),[help,setHelp]=useState<string[]>(stored?.specialties||enrollment?.profile.specialties||[]),[languages,setLanguages]=useState<string[]>(stored?.languages||enrollment?.profile.languages||[]),[unlocking,setUnlocking]=useState(false),[error,setError]=useState('');const toggle=(list:string[],value:string,set:(values:string[])=>void)=>set(list.includes(value)?list.filter(item=>item!==value):[...list,value]);const draft={name:name.trim(),specialties:help,languages};const next=async()=>{saveProfileDraft(draft);sessionStorage.setItem('counselor-name',draft.name);if(!enrollment){go('/counselor/security');return}if(!accountVault.isUnlocked()){setUnlocking(true);return}setError('');try{const createdAt=Math.max(Math.floor(Date.now()/1000),enrollment.profile_event.created_at+1);const updated=await counselorApi().updateCounselorEnrollmentProfile(enrollment.id,signProfile(draft,createdAt));saveEnrollment(updated);go('/counselor/review')}catch(caught){setError(caught instanceof Error?caught.message:'The profile could not be updated.')}};if(unlocking)return <Screen title="Edit profile" back><PinUnlock title="Unlock your account" text="Enter your PIN to sign the updated profile." unlock={async pin=>{await accountVault.unlock(pin);setUnlocking(false);window.setTimeout(()=>void next(),0)}}/></Screen>;return <Screen title="Your profile" back className="co-profile"><label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Counselor Grace"/><small>Use a first name or a professional name, not your full name.</small></label><fieldset><legend>What you help with</legend><div>{helpOptions.map(value=><button type="button" className={help.includes(value)?'selected':''} onClick={()=>toggle(help,value,setHelp)} key={value}>{value}</button>)}</div></fieldset><fieldset><legend>Languages</legend><div>{languageOptions.map(value=><button type="button" className={languages.includes(value)?'selected':''} onClick={()=>toggle(languages,value,setLanguages)} key={value}>{value}</button>)}</div></fieldset><section className="co-preview"><small>HOW SURVIVORS WILL SEE YOU</small><strong>{name||'Your display name'}</strong><span>◷ {enrollment?'Profile update pending':'Not verified yet'}</span></section>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" disabled={!name.trim()||!help.length||!languages.length} onClick={()=>void next()}>Continue</button></Screen>}

function Security(){const profile=readProfileDraft();const invite=sessionStorage.getItem('counselor-invite');const [existing,setExisting]=useState<boolean|null>(null),[pin,setPin]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{void accountVault.summary().then(value=>setExisting(Boolean(value)))},[]);const ready=/^\d{4}$/.test(pin)&&(existing||pin===confirm);const submit=async()=>{if(!profile||!invite)return;setBusy(true);setError('');let created=false;try{if(existing)await accountVault.unlock(pin);else{await accountVault.create(pin,profile.name);created=true}const enrollment=await counselorApi().claimCounselorInvite(invite,signProfile(profile));saveEnrollment(enrollment);sessionStorage.removeItem('counselor-invite');go(created?'/counselor/backup':'/counselor/credentials')}catch(caught){if(created)await accountVault.clear();setError(caught instanceof Error?caught.message:'The invitation could not be claimed.');setBusy(false)}};if(!profile||!invite)return <Screen title="Secure your account" back><ChatNotice action={{label:'Restart onboarding',run:()=>go('/counselor')}}>Your invite or profile is missing from this browser.</ChatNotice></Screen>;return <Screen title="Secure your account" back className="co-security"><h2>{existing?'Use your account on this phone':'Create your private PIN'}</h2><p>{existing?'Unlock the identity already protected on this phone. The organisation will verify that identity.':'Your identity key and backup words are generated on this device. The PIN never goes to Resilience.'}</p><label>{existing?'Your 4-digit PIN':'Choose a 4-digit PIN'}<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" type="password" autoComplete={existing?'current-password':'new-password'}/></label>{!existing&&<label>Confirm your PIN<input value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" type="password" autoComplete="new-password"/></label>}<aside>▢ <span>Your key is encrypted with device-bound Web Crypto and PIN-derived protection.</span></aside>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" disabled={!ready||busy||existing===null} onClick={()=>void submit()}>{busy?'Creating your secure application…':'Continue securely'}</button></Screen>}

function CounselorBackup(){const [words,setWords]=useState<string[]|null>(null),[copied,setCopied]=useState(false),[error,setError]=useState('');const copy=async()=>{if(!words)return;await navigator.clipboard.writeText(backupPhrase(words));setCopied(true);window.setTimeout(()=>setCopied(false),1500)};const download=()=>{if(!words)return;const url=URL.createObjectURL(new Blob([backupDownloadText(words)],{type:'text/plain;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='resilience-counselor-backup.txt';anchor.click();URL.revokeObjectURL(url)};const done=async()=>{await accountVault.confirmBackup();go('/counselor/credentials')};return <Screen title="Back up your account" back className="co-backup">{!words?<PinUnlock title="Reveal your backup words" text="Enter your PIN. Your words are decrypted only on this device." unlock={async pin=>{const phrase=await accountVault.revealBackupWords(pin);setWords(phrase.split(' '))}}/>:<><p>Write these words down in order and keep them somewhere private. Anyone with them can access this counselor account.</p><ol>{words.map((word,index)=><li key={`${word}-${index}`}><small>{index+1}</small><strong>{word}</strong></li>)}</ol><div className="co-backup-actions"><button className="co-secondary" onClick={()=>void copy()}>{copied?'Copied':'Copy words'}</button><button className="co-secondary" onClick={download}>Download</button></div><aside>⚠ <span>Resilience support and partner organisations will never ask for these words.</span></aside>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" onClick={()=>void done().catch(()=>setError('Could not confirm the backup. Try again.'))}>I’ve stored them safely</button></>}</Screen>}

const credentialSlots:{slot:CredentialSlot;label:string;required:boolean}[]=[{slot:'certificate',label:'Counselling licence or certificate',required:true},{slot:'letter',label:'Letter from your organisation',required:true},{slot:'supporting',label:'Other supporting document (optional)',required:false}]
function Credentials(){const [enrollment,setEnrollment]=useState<CounselorEnrollment|null>(readEnrollment()),[unlocked,setUnlocked]=useState(accountVault.isUnlocked()),[docs,setDocs]=useState<SelectedCredential[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const choose=(slot:CredentialSlot,label:string,required:boolean,file?:File)=>{if(!file)return;if(file.size>6*1024*1024){setError(`${label} must be smaller than 6 MB.`);return}if(!['application/pdf','image/jpeg','image/png'].includes(file.type)){setError(`${label} must be a PDF, JPEG, or PNG.`);return}setError('');setDocs(current=>[...current.filter(item=>item.slot!==slot),{slot,label,file,required}])};const ready=credentialSlots.filter(item=>item.required).every(item=>docs.some(doc=>doc.slot===item.slot));const submit=async()=>{if(!enrollment||!ready)return;setBusy(true);setError('');try{const encrypted=[];for(const document of docs)encrypted.push(await encryptCredential(document.file,enrollment.credential_recipient_pubkey));const updated=await counselorApi().submitCounselorCredentials(enrollment.id,encrypted);saveEnrollment(updated);go('/counselor/review')}catch(caught){setError(caught instanceof Error?caught.message:'The encrypted documents could not be sent.');setBusy(false)}};if(!unlocked)return <Screen title="Your credentials" back><PinUnlock title="Unlock your account" text="Your PIN unlocks the key used to encrypt and submit your documents." unlock={async pin=>{await accountVault.unlock(pin);const current=await recoverEnrollment();setEnrollment(current);setUnlocked(true)}}/></Screen>;if(!enrollment)return <Screen title="Your credentials" back><ChatNotice action={{label:'Return to invitation',run:()=>go('/counselor')}}>No counselor application was found for this identity.</ChatNotice></Screen>;return <Screen title="Your credentials" back className="co-credentials"><p>{enrollment.organization_name} checks your documents before you can talk to anyone.</p><div className="co-docs">{credentialSlots.map(item=>{const selected=docs.find(doc=>doc.slot===item.slot);return <section key={item.slot}><label>{item.label}</label><label className={`co-file ${selected?'selected':''}`}><span>▤</span><span><strong>{selected?`${selected.file.name} · ${(selected.file.size/1024/1024).toFixed(1)} MB`:'Choose a PDF or image'}</strong><small>{selected?'Ready to encrypt on submission':item.required?'Required':'Optional'}</small></span><input type="file" hidden accept="application/pdf,image/jpeg,image/png" onChange={event=>choose(item.slot,item.label,item.required,event.target.files?.[0])}/></label></section>})}</div><aside>▢ <span>Files are encrypted on this phone for {enrollment.organization_name}. Resilience receives ciphertext only and removes it after review.</span></aside>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" disabled={!ready||busy} onClick={()=>void submit()}>{busy?'Encrypting and sending…':'Submit for review'}</button></Screen>}

function useEnrollmentStatus(){const [enrollment,setEnrollment]=useState<CounselorEnrollment|null>(readEnrollment()),[unlocked,setUnlocked]=useState(accountVault.isUnlocked()),[loading,setLoading]=useState(false),[error,setError]=useState('');const refresh=async()=>{setLoading(true);setError('');try{const current=await recoverEnrollment();setEnrollment(current)}catch(caught){setError(caught instanceof Error?caught.message:'Could not load your verification status.')}finally{setLoading(false)}};useEffect(()=>{if(!unlocked)return;const initial=window.setTimeout(()=>void refresh(),0);const timer=window.setInterval(()=>void refresh(),15000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[unlocked]);return{enrollment,unlocked,loading,error,unlock:async(pin:string)=>{await accountVault.unlock(pin);setUnlocked(true)},refresh}}
function Review(){const state=useEnrollmentStatus();if(!state.unlocked)return <Screen title="Verification" className="co-status"><PinUnlock title="Check your application" text="Enter your PIN to securely ask for the latest review status." unlock={state.unlock}/></Screen>;if(!state.enrollment)return <Screen title="Verification" className="co-status"><ChatNotice action={{label:'Try again',run:()=>void state.refresh()}}>{state.loading?'Loading your application…':state.error||'No counselor application was found.'}</ChatNotice></Screen>;const enrollment=state.enrollment;if(enrollment.status==='more_information')return <MoreInfo enrollment={enrollment}/>;if(enrollment.status==='rejected')return <Screen title="Verification" className="co-status"><section><span className="co-status-icon attention">!</span><h2>Your application wasn’t approved</h2><p>{enrollment.review_message||`${enrollment.organization_name} could not approve this application.`}</p></section></Screen>;if(enrollment.directory_status==='verified')return <Verified enrollment={enrollment}/>;if(enrollment.status==='approved')return <Screen title="Verification" className="co-status"><section><span className="co-status-icon pending">◷</span><h2>Your credentials are approved</h2><p>{enrollment.organization_name} must now add your key to its signed counselor roster before survivors see the verified badge.</p><ul><li className="done">✓ <span>Credentials approved</span></li><li className="waiting">◷ <span>Signed roster publication pending</span></li><li>♢ <span>Verified badge added to your profile</span></li></ul></section><button className="co-secondary" onClick={()=>void state.refresh()}>{state.loading?'Checking…':'Check again'}</button></Screen>;return <Screen title="Verification" className="co-status"><section><span className="co-status-icon pending">◷</span><h2>Your documents are with {enrollment.organization_name}</h2><p>Most reviews take 1 to 3 working days. We’ll let you know with a discreet notification.</p><ul><li className="done">✓ <span>Encrypted documents sent</span></li><li className="waiting">◷ <span>Organisation review: in progress</span></li><li>♢ <span>Verified badge added to your profile</span></li></ul></section>{state.error&&<p className="co-error" role="alert">{state.error}</p>}<button className="co-secondary" onClick={()=>go('/counselor/profile')}>Edit my profile</button></Screen>}
function MoreInfo({enrollment=readEnrollment()}:{enrollment?:CounselorEnrollment|null}){if(!enrollment)return <Screen title="Verification" className="co-status"><ChatNotice action={{label:'Check application',run:()=>go('/counselor/review')}}>Unlock your account to load the organisation’s request.</ChatNotice></Screen>;return <Screen title="Verification" className="co-status"><section><span className="co-status-icon attention">!</span><h2>{enrollment.organization_name} needs one more thing</h2><article><small>MESSAGE FROM YOUR ORGANISATION</small><p>{enrollment.review_message||'Please upload replacement credentials.'}</p></article></section><button className="co-primary" onClick={()=>go('/counselor/credentials')}>Upload again</button></Screen>}
function Verified({enrollment=readEnrollment()}:{enrollment?:CounselorEnrollment|null}){if(!enrollment)return <Screen title="Verification" className="co-status"><ChatNotice action={{label:'Check application',run:()=>go('/counselor/review')}}>Unlock your account to load your verified profile.</ChatNotice></Screen>;return <Screen title="Verification" className="co-status"><section><span className="co-status-icon verified">✓</span><h2>You’re verified</h2><p>{enrollment.organization_name} confirmed your credentials and placed your key on its signed roster. Survivors now see:</p><article className="verified-card"><strong>{enrollment.profile.name}</strong><span>♢ Verified by {enrollment.organization_name}</span><small>Your organisation can renew, expire, or remove this verification.</small></article><aside>◉ <span>Resilience removed the encrypted credentials after the review. Only the verification appears on your profile.</span></aside></section><button className="co-primary" onClick={()=>go('/counselor/inbox')}>Go to my inbox</button></Screen>}

type InboxTab='requests'|'active'
function CounselorNav({active='inbox'}:{active?:'inbox'|'wallet'|'settings'}){return <nav className="co-nav" aria-label="Counselor navigation"><a className={active==='inbox'?'active':''} href="/counselor/inbox"><span>▱</span>Inbox</a><a className={active==='wallet'?'active':''} href="/counselor/wallet"><span>▣</span>Wallet</a><a className={active==='settings'?'active':''} href="/counselor/settings"><span>⚙</span>Settings</a></nav>}
function Inbox(){const [available,setAvailable]=useState(sessionStorage.getItem('counselor-available')!=='false'),[tab,setTab]=useState<InboxTab>('requests'),[availabilityError,setAvailabilityError]=useState('');const chat=useMessenger('counselor',false);const all=chat.state.kind==='ready'?conversationsOf(chat.messages):[];const fresh=all.filter(item=>!item.repliedByMe),active=all.filter(item=>item.repliedByMe);const shown=tab==='requests'?fresh:active;const updateAvailability=async()=>{if(chat.state.kind!=='ready')return;const next=!available;setAvailable(next);setAvailabilityError('');try{await counselorApi().setCounselorAvailability(next,'Weekdays 9:00–17:00');sessionStorage.setItem('counselor-available',String(next))}catch(caught){setAvailable(!next);setAvailabilityError(caught instanceof Error?caught.message:'Availability could not be updated.')}};
let body:React.ReactNode;
if(chat.state.kind==='no-account')body=<ChatNotice action={{label:'Sign in',run:()=>go('/counselor/sign-in')}}>Sign in with your backup words to see messages from survivors.</ChatNotice>;
else if(chat.state.kind==='locked')body=<PinUnlock title={`Welcome back, ${chat.state.nickname}`} text="Enter your PIN to open your inbox." unlock={chat.unlock}/>;
else if(chat.state.kind==='error')body=<ChatNotice action={{label:'Try again',run:()=>void chat.retry()}}>{chat.state.message}</ChatNotice>;
else if(chat.state.kind!=='ready')body=<p className="chat-empty">Connecting securely…</p>;
else body=<section className="co-chat-list">{tab==='active'&&<small className="co-list-label">ACTIVE</small>}{shown.map(item=><button className="co-chat-row" onClick={()=>go(`/counselor/chat/${item.peer}`)} key={item.conversationId}><span className="co-avatar">{item.peerName.charAt(0).toUpperCase()}</span><span><strong>{item.peerName} {!item.peerIsGuest&&!item.repliedByMe&&<small>New</small>}</strong><span>{item.last.fromMe?'You: ':''}{item.last.text}</span></span><time>{timeLabel(item.last.createdAt)}</time></button>)}{shown.length===0&&<p className="chat-empty">{tab==='requests'?'No new requests. New conversations from survivors appear here.':'No active conversations yet.'}</p>}</section>;
return <main className="co-screen co-work"><Header title="Inbox"/><section className="co-availability"><span><strong>You’re {available?'available':'unavailable'}</strong><small>{available?'Survivors can send you new requests.':'New requests are paused.'}</small></span><button role="switch" aria-checked={available} className={available?'on':''} disabled={chat.state.kind!=='ready'} onClick={()=>void updateAvailability()}><i/></button></section>{availabilityError&&<p className="co-error" role="alert">{availabilityError}</p>}<div className="co-tabs" role="tablist"><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}>New requests · {fresh.length}</button><button className={tab==='active'?'active':''} onClick={()=>setTab('active')}>Active · {active.length}</button></div>{body}<aside className="co-privacy-note">◉ <span>People appear by nickname only. You never see a phone number, location or account ID.</span></aside><CounselorNav/></main>}

// A real conversation with one survivor, addressed by her public key.
function LiveChat({peer}:{peer:string}){const chat=useMessenger('counselor',false);const [message,setMessage]=useState(''),[error,setError]=useState('');const thread=chat.messages.filter(item=>item.peer===peer);const name=thread.find(item=>!item.fromMe)?.peerName??'Survivor';const guest=thread.some(item=>item.peerIsGuest);const send=async()=>{if(!message.trim()||!chat.messenger)return;const text=message;setMessage('');setError('');try{await chat.messenger.send(peer,name,text)}catch{setMessage(text);setError('That message couldn’t be sent. Try again.')}};
let body:React.ReactNode;
if(chat.state.kind==='no-account')body=<ChatNotice action={{label:'Sign in',run:()=>go('/counselor/sign-in')}}>Sign in with your backup words first.</ChatNotice>;
else if(chat.state.kind==='locked')body=<PinUnlock title={`Welcome back, ${chat.state.nickname}`} text="Enter your PIN to open this conversation." unlock={chat.unlock}/>;
else if(chat.state.kind==='error')body=<ChatNotice action={{label:'Try again',run:()=>void chat.retry()}}>{chat.state.message}</ChatNotice>;
else if(chat.state.kind!=='ready')body=<p className="chat-empty">Connecting securely…</p>;
else body=<section className="co-thread">{thread.length===0&&<p className="chat-empty">No messages in this conversation on this phone.</p>}{thread.map(item=><p className={item.fromMe?'sent':'received'} key={item.id}>{item.text}{item.fromMe&&<small>{deliveryLabel(item)}</small>}</p>)}</section>;
const ready=chat.state.kind==='ready'&&thread.length>0;
return <main className="co-screen co-work-chat"><Header title={name} back/>{ready&&<span className="co-guest-tag">{guest?'Guest':'Account'}</span>}{ready&&guest&&<aside className="co-chat-warning">ⓘ <span>Guest: this conversation clears when she leaves. Don’t ask for her name, phone number or location.</span></aside>}{body}{ready&&<div className="co-tools"><button>▣ Share a resource</button><button>↗ Refer</button><button>♧ Emergency numbers</button><button disabled={guest} onClick={()=>go('/counselor/support-request')}>▢ Request support</button></div>}{ready&&guest&&<small className="co-tool-hint">Request support is available when she has an account.</small>}{error&&<small className="co-error" role="alert">{error}</small>}{ready&&<form className="co-composer" onSubmit={event=>{event.preventDefault();void send()}}><input aria-label="Message" value={message} maxLength={2000} onChange={event=>setMessage(event.target.value)} placeholder="Write a message…"/><button disabled={!message.trim()} aria-label="Send message">➤</button></form>}</main>}

function WorkChat({person}:{person:string}){const guest=person!=='Amani';const [message,setMessage]=useState('');useEffect(()=>{if(!guest)return;const timer=window.setTimeout(()=>go('/counselor/chat-ended'),8000);return()=>window.clearTimeout(timer)},[guest]);return <main className="co-screen co-work-chat"><Header title={person} back/><span className="co-guest-tag">{guest?'Guest':'Account'}</span>{guest&&<aside className="co-chat-warning">ⓘ <span>Guest: this conversation clears when she leaves. Don’t ask for her name, phone number or location.</span></aside>}<section className="co-thread"><p className="received">{person==='Sky 42'?'I need someone to talk to':'Things at home are getting worse. I don’t know where to go.'}</p><p className="sent">I’m here, {person}. Take your time. I’m listening.<small>Sent</small></p><p className="received">Things at home are getting worse.<br/>I don’t know where to go.</p><p className="sent">Thank you for telling me. Would it help to look at safe places near you together?<small>Sending</small></p></section><div className="co-tools"><button>▣ Share a resource</button><button>↗ Refer</button><button>♧ Emergency numbers</button><button disabled={guest} onClick={()=>go('/counselor/support-request')}>▢ Request support</button></div>{guest&&<small className="co-tool-hint">Request support is available when she has an account.</small>}<form className="co-composer" onSubmit={event=>{event.preventDefault();setMessage('')}}><input aria-label="Message" value={message} onChange={event=>setMessage(event.target.value)} placeholder="Write a message…"/><button disabled={!message.trim()} aria-label="Send message">➤</button></form></main>}

function ChatEnded(){return <Screen title="Sky 42" back className="co-status co-ended"><section><span className="co-status-icon">▣</span><h2>Sky 42 has left</h2><p>Guest conversations end when she leaves Resilience. You can’t message her again, and she can’t see this conversation any more.</p></section><button className="co-primary" onClick={()=>go('/counselor/inbox')}>Back to inbox</button></Screen>}

const amounts=['KES 1,000','KES 2,500','KES 5,000','Other amount'],reasons=['Transport to safety','Medical costs','Food and essentials','Legal fees','Other']
const reasonCodes:Record<string,'transport'|'pharmacy'|'shelter'|'food'|'other'>={'Transport to safety':'transport','Medical costs':'pharmacy','Food and essentials':'food','Legal fees':'other','Other':'other'}
function SupportRequest(){const enrollment=readEnrollment();const [amount,setAmount]=useState('KES 2,500'),[customAmount,setCustomAmount]=useState(''),[reason,setReason]=useState('Transport to safety'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const amountKes=amount==='Other amount'?Number(customAmount.replace(/\D/g,'')):Number(amount.replace(/\D/g,''));const submit=async()=>{if(!enrollment||!amountKes||!accountVault.isUnlocked())return;setBusy(true);setError('');try{const request=await counselorApi().createDisbursement(enrollment.organization_id,{amount_kes:amountKes,amount_sat:amountKes,rate_source:'prototype-kes-parity',reason_code:reasonCodes[reason],note:note.trim()||null});sessionStorage.setItem('counselor-support-request',JSON.stringify(request));go('/counselor/support-request/sent')}catch(caught){setError(caught instanceof Error?caught.message:'The support request could not be sent.');setBusy(false)}};if(!enrollment)return <Screen title="Request support" back><ChatNotice action={{label:'Check verification',run:()=>go('/counselor/review')}}>Your verified organisation could not be found on this phone.</ChatNotice></Screen>;if(!accountVault.isUnlocked())return <Screen title="Request support" back><PinUnlock title="Unlock your counselor account" text="Enter your PIN to sign this support request." unlock={async pin=>{await accountVault.unlock(pin);window.location.reload()}}/></Screen>;return <Screen title="Request support" back className="co-request"><strong>For this account holder</strong><fieldset><legend>Amount</legend><div>{amounts.map(value=><button className={amount===value?'selected':''} onClick={()=>setAmount(value)} key={value}>{value}</button>)}</div></fieldset>{amount==='Other amount'&&<label className="co-custom-amount">Custom amount<input value={customAmount} onChange={event=>setCustomAmount(event.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="KES 0"/></label>}<small>Paid from {enrollment.organization_name}’s fund.</small><fieldset><legend>Reason</legend><div>{reasons.map(value=><button className={reason===value?'selected':''} onClick={()=>setReason(value)} key={value}>{value}</button>)}</div></fieldset><label>Note for your organisation (optional)<textarea value={note} maxLength={500} onChange={event=>setNote(event.target.value)} placeholder="e.g. Needs fare to reach a shelter tonight"/></label><small>Don’t include a real name, phone number, location, nickname, or account ID.</small><aside>◉ <span>{enrollment.organization_name} sees the amount, reason, note and your counselor key. They do not see who the recipient is.</span></aside>{error&&<p className="co-error" role="alert">{error}</p>}<button className="co-primary" disabled={!amountKes||busy} onClick={()=>void submit()}>{busy?'Sending securely…':'Send request'}</button></Screen>}
function SupportSent(){let request:Disbursement|null=null;try{const stored=sessionStorage.getItem('counselor-support-request');request=stored?JSON.parse(stored) as Disbursement:null}catch{/* A missing local receipt is safe; the server remains authoritative. */}const enrollment=readEnrollment();return <Screen title="Request support" className="co-status co-request-sent"><section><span className="co-status-icon verified">✓</span><h2>Request sent to {enrollment?.organization_name||'your organisation'}</h2><p>{request?`KES ${request.amount_kes.toLocaleString()} is awaiting independent approval.`:'The request was signed and submitted without survivor identity data.'}</p><strong className="co-pending">● {request?.state==='CREATED'?'Pending approval':request?.state||'Submitted'}</strong></section><button className="co-primary" onClick={()=>history.back()}>Back to chat</button></Screen>}

const counselorPayments=[{icon:'✓',title:'Monthly payment',meta:'Partner organisation A · Received',amount:'+KES 7,800',state:'received'},{icon:'◷',title:'Session support',meta:'Partner organisation A · Pending',amount:'+KES 3,100',state:'pending'},{icon:'↥',title:'Withdrawal to M-Pesa',meta:'Completed',amount:'−KES 3,900',state:'complete'},{icon:'!',title:'Payment request',meta:'Expired',amount:'KES 3,100',state:'expired'}]
function CounselorWallet(){const enrollment=readEnrollment(),orgId=enrollment?.organization_id;const [copied,setCopied]=useState(false),[requests,setRequests]=useState<Disbursement[]>([]),[error,setError]=useState('');useEffect(()=>{if(!orgId||!accountVault.isUnlocked())return;counselorApi().listDisbursements(orgId).then(setRequests).catch(caught=>setError(caught instanceof Error?caught.message:'Could not load support requests.'))},[orgId]);const copy=async()=>{try{await navigator.clipboard.writeText('grace@pay.example')}catch{/* Clipboard can be unavailable outside HTTPS. */}setCopied(true);window.setTimeout(()=>setCopied(false),1600)};if(!accountVault.isUnlocked())return <Screen title="Wallet"><PinUnlock title="Unlock counselor wallet" text="Enter your PIN to load signed support requests." unlock={async pin=>{await accountVault.unlock(pin);window.location.reload()}}/></Screen>;return <main className="co-screen co-work co-wallet"><Header title="Wallet"/><p className="co-test-mode">TEST MODE: NO REAL MONEY</p><section className="co-balance"><small>Balance</small><h2>KES 10,900</h2><p>Paid by your organisation. Withdraw to M-Pesa any time.</p><div><button onClick={()=>go('/app/wallet/withdraw')}>Withdraw</button><button onClick={copy}>Receive</button></div></section><section className="co-address"><strong>Your payment address</strong><p><span>grace@pay.example</span><button onClick={copy}>{copied?'Copied':'Copy'}</button></p><small>Share this with your organisation so they can pay you.</small></section><small className="co-list-label">SUPPORT REQUESTS</small>{error&&<p className="co-error" role="alert">{error}</p>}<section className="co-payments">{requests.map(request=><article key={request.id}><span className={request.state==='CREATED'?'pending':'received'}>{request.state==='CREATED'?'◷':'✓'}</span><span><strong>{request.reason_code.replace('_',' ')}</strong><small>{enrollment?.organization_name} · {request.state}</small></span><strong>KES {request.amount_kes.toLocaleString()}</strong></article>)}{requests.length===0&&<small>No support requests yet.</small>}{counselorPayments.map(payment=><article key={payment.title}><span className={payment.state}>{payment.icon}</span><span><strong>{payment.title}</strong><small>{payment.meta}</small></span><strong>{payment.amount}</strong></article>)}</section><CounselorNav active="wallet"/></main>}

function CounselorSettings(){const enrollment=readEnrollment();const initial=sessionStorage.getItem('counselor-available')!=='false';const [available,setAvailable]=useState(initial),[error,setError]=useState('');const updateAvailability=async()=>{if(!accountVault.isUnlocked()){setError('Unlock your counselor account from the inbox first.');return}const next=!available;setAvailable(next);setError('');try{await counselorApi().setCounselorAvailability(next,'Weekdays 9:00–17:00');sessionStorage.setItem('counselor-available',String(next))}catch(caught){setAvailable(!next);setError(caught instanceof Error?caught.message:'Availability could not be updated.')}};return <main className="co-screen co-work co-settings"><Header title="Settings"/><small className="co-list-label">AVAILABILITY</small><section><div><span>Available for new requests</span><button role="switch" aria-checked={available} className={`co-settings-switch ${available?'on':''}`} onClick={()=>void updateAvailability()}><i/></button></div><button><span>Working hours</span><small>Weekdays 9:00–17:00</small></button></section>{error&&<p className="co-error" role="alert">{error}</p>}<small className="co-list-label">PROFILE</small><section><button onClick={()=>go('/counselor/profile')}><span>Display name</span><small>{sessionStorage.getItem('counselor-name')||'Counselor'}</small></button><button onClick={()=>go('/counselor/profile')}><span>Focus areas and languages</span><small>{enrollment?.profile.specialties.length||0} selected</small></button></section><small className="co-list-label">VERIFICATION</small><section className="co-verification"><strong>♢ Verified by {enrollment?.organization_name||'your organisation'}</strong><small>{enrollment?.directory_status==='verified'?'Current signed roster verification':'Verification status pending'}</small></section><small className="co-list-label">SAFETY</small><section><button onClick={()=>go('/app/settings/notifications')}><span>Notifications</span><small>Discreet</small></button><button onClick={()=>go('/app/settings/timer')}><span>Auto-exit timer</span><small>2 minutes</small></button><button onClick={()=>go('/app/settings/pin')}><span>Change PIN</span></button></section><button className="co-sign-out" onClick={()=>{accountVault.lock();window.location.replace('/')}}>Sign out</button><CounselorNav active="settings"/></main>}

export default function CounselorOnboarding(){const path=window.location.pathname;if(path.endsWith('/profile'))return <Profile/>;if(path.endsWith('/security'))return <Security/>;if(path.endsWith('/backup'))return <CounselorBackup/>;if(path.endsWith('/credentials'))return <Credentials/>;if(path.endsWith('/review'))return <Review/>;if(path.endsWith('/more-information'))return <MoreInfo/>;if(path.endsWith('/verified'))return <Verified/>;if(path.endsWith('/inbox'))return <Inbox/>;if(path.endsWith('/wallet'))return <CounselorWallet/>;if(path.endsWith('/settings'))return <CounselorSettings/>;if(path.endsWith('/chat-ended'))return <ChatEnded/>;if(path.endsWith('/support-request/sent'))return <SupportSent/>;if(path.endsWith('/support-request'))return <SupportRequest/>;if(path.endsWith('/sign-in'))return <SignIn/>;if(path.includes('/chat/')){const slug=path.split('/').pop()??'';if(/^[0-9a-f]{64}$/.test(slug))return <LiveChat peer={slug} key={slug}/>;const person=slug==='sky-42'?'Sky 42':slug==='amani'?'Amani':slug==='hope'?'Hope':'River';return <WorkChat person={person}/>}return <Invite/>}
