import { useEffect, useRef, useState } from 'react'
import { backupDownloadText, backupPhrase } from '../security/backupExport'
import { clearPrivateDeviceData } from '../security/lifecycle'
import { accountVault } from '../security/vault'
import './settings.css'

type IconName = 'back' | 'exit' | 'home' | 'chat' | 'wallet' | 'settings' | 'arrow' | 'info' | 'eye' | 'copy' | 'download' | 'phone' | 'lock' | 'warn' | 'check' | 'user' | 'trash'
const paths: Record<IconName, React.ReactNode> = {
  back: <path d="m15 18-6-6 6-6" />, exit: <><path d="M10 5H5v14h5" /><path d="m14 8 4 4-4 4M8 12h10" /></>,
  home: <><path d="m3 11 9-8 9 8" /><path d="M5 10v11h14V10M9 21v-7h6v7" /></>, chat: <path d="M20 11.5a8 8 0 0 1-9.1 7.9L5 21l1.6-4A8 8 0 1 1 20 11.5Z" />, wallet: <><path d="M3 6h15a2 2 0 0 1 2 2v11H5a2 2 0 0 1-2-2V6Z" /><path d="M15 11h6v5h-6a2 2 0 0 1 0-5Z" /></>, settings: <><circle cx="12" cy="12" r="3" /><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2" /></>,
  arrow: <path d="m9 5 7 7-7 7" />, info: <><circle cx="12" cy="12" r="9" /><path d="M12 11v6M12 7h.01" /></>, eye: <><path d="M3 12s3.5-6 9-6 9 6 9 6-3.5 6-9 6-9-6-9-6Z" /><circle cx="12" cy="12" r="2.5" /></>, copy: <><rect x="8" y="8" width="11" height="11" rx="2" /><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3" /></>, download: <><path d="M12 3v12M7 10l5 5 5-5" /><path d="M5 20h14" /></>, phone: <path d="M7 3h3l1.2 5-2 1.2a15 15 0 0 0 5.6 5.6l1.2-2 5 1.2v3c0 2-1 4-4 4C9.3 21 3 14.7 3 7c0-3 2-4 4-4Z" />, lock: <><rect x="5" y="10" width="14" height="11" rx="2" /><path d="M8 10V7a4 4 0 0 1 8 0v3" /></>, warn: <><path d="M12 3 2.5 20h19L12 3Z" /><path d="M12 9v4M12 17h.01" /></>, check: <path d="m5 12 4 4L19 6" />, user: <><circle cx="12" cy="8" r="3" /><path d="M6 20a6 6 0 0 1 12 0" /></>, trash: <><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14" /></>,
}
function Icon({ name, size = 23 }: { name: IconName; size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg> }
const guest = () => new URLSearchParams(window.location.search).get('mode') === 'guest'
const mode = () => guest() ? '?mode=guest' : ''
const go = (path: string) => window.location.assign(`${path}${mode()}`)
function Header({ title, root = false }: { title: string; root?: boolean }) { return <header className="settings-header">{!root && <button className="settings-back" onClick={() => history.back()} aria-label="Go back"><Icon name="back" size={18} /></button>}<h1>{title}</h1><button className="settings-exit" onClick={() => window.location.replace('/')}><Icon name="exit" size={17} />Exit</button></header> }
function Nav() { return <nav className="settings-nav"><a href={`/app${mode()}`}><Icon name="home" /><span>Home</span></a><a href={`/app/messages${mode()}`}><Icon name="chat" /><span>Messages</span></a>{guest() ? <a href={`/app${mode()}`}><Icon name="wallet" /><span>Wallet</span></a> : <a href="/app/wallet"><Icon name="wallet" /><span>Wallet</span></a>}<a className="active" href={`/app/settings${mode()}`}><Icon name="settings" /><span>Settings</span></a></nav> }
function Screen({ children, title, root = false, className = '' }: React.PropsWithChildren<{ title: string; root?: boolean; className?: string }>) { return <div className={`settings-screen ${className}`}><Header title={title} root={root} />{children}<Nav /></div> }
function Row({ children, sub, danger, onClick }: React.PropsWithChildren<{ sub?: string; danger?: boolean; onClick: () => void }>) { return <button className={`settings-row ${danger ? 'danger' : ''}`} onClick={onClick}><span><strong>{children}</strong>{sub && <small>{sub}</small>}</span><Icon name="arrow" size={18} /></button> }

function SettingsHome() {
  const timer = localStorage.getItem('auto-exit-minutes') || '2'
  if (guest()) return <Screen title="Settings" root><button className="create-account-card" onClick={() => window.location.assign('/onboarding/create')}><Icon name="user" /><span><strong>Create an account</strong><small>Keep your circle, wallet, records and messages</small></span><Icon name="arrow" /></button><Section title="Safety"><Row onClick={() => go('/app/settings/timer')} sub={`${timer} minutes`}>Auto-exit timer</Row></Section><Section title="Privacy"><Row onClick={() => go('/app/settings/privacy')}>How your privacy works</Row><Row onClick={() => {}}>Language: English</Row></Section></Screen>
  return <Screen title="Settings" root><Section title="Safety"><Row onClick={() => go('/app/settings/notifications')}>Notifications</Row><Row onClick={() => go('/app/settings/timer')} sub={`${timer} minutes`}>Auto-exit timer</Row><Row onClick={() => go('/app/settings/pin')}>Change PIN</Row></Section><Section title="Private"><Row onClick={() => go('/app/records')} sub="Health notes only you can see">My records</Row></Section><Section title="Account"><Row onClick={() => go('/app/settings/account-id')}>Your account ID</Row><Row onClick={() => go('/app/settings/backup')} sub={localStorage.getItem('account-backed-up') ? 'Backed up' : '⚠ Not backed up'}>Back up your account</Row><Row onClick={() => go('/app/settings/account-safety')}>I think someone accessed my account</Row></Section><Section title="Privacy"><Row onClick={() => go('/app/settings/privacy')}>How your privacy works</Row><Row danger onClick={() => go('/app/settings/clear')}>Clear everything from this phone</Row></Section><Section><Row onClick={() => {}}>Language: English</Row></Section></Screen>
}
function Section({ title, children }: React.PropsWithChildren<{ title?: string }>) { return <section className="settings-section">{title && <h2>{title}</h2>}<div>{children}</div></section> }
function Timer() { const [selected, setSelected] = useState(localStorage.getItem('auto-exit-minutes') || '2'); const select = (value: string) => { setSelected(value); localStorage.setItem('auto-exit-minutes', value) }; return <Screen title="Auto-exit timer"><p className="settings-lead">If you stop using Resilience for this long, it hides itself. Typing doesn’t count.</p><div className="choice-list">{['1', '2', '5'].map((value) => <button className={selected === value ? 'selected' : ''} onClick={() => select(value)} key={value}><i>{selected === value && <Icon name="check" size={14} />}</i><strong>{value} minute{value !== '1' ? 's' : ''}</strong>{value === '2' && <small>Default</small>}</button>)}</div><p className="settings-note">The app also hides straight away when you switch to another app or your screen turns off.</p></Screen> }
function Privacy() { const cards: Array<[IconName, string]> = guest() ? [['phone', 'What you read here stays on this phone.'], ['user', 'People you talk to see only your nickname.'], ['trash', "Clearing the app removes it from this phone, but people you've messaged may still have copies."], ['trash', 'Without an account, everything is cleared when you exit or the app hides itself.']] : [['phone', 'Your conversations are saved on this phone, protected by your PIN.'], ['user', 'People you talk to see only your nickname.'], ['trash', "Clearing the app removes it from this phone, but people you've messaged may still have copies."]]; return <Screen title="How your privacy works"><main className="privacy-cards">{cards.map(([icon, text]) => <article key={text}><span><Icon name={icon} /></span><p>{text}</p></article>)}<p>Designed to keep identifying information to a minimum.</p></main></Screen> }
function Notifications() { const [value, setValue] = useState(localStorage.getItem('notification-mode') || 'discreet'); const choose = (next: string) => { setValue(next); localStorage.setItem('notification-mode', next) }; return <Screen title="Notifications"><p className="notice"><Icon name="info" />Notifications never show what a message says or who sent it.</p><div className="choice-list notification-choices"><button className={value === 'silent' ? 'selected' : ''} onClick={() => choose('silent')}><i />Silent: no notifications</button><button className={value === 'discreet' ? 'selected' : ''} onClick={() => choose('discreet')}><i />Discreet: shows “You have a new update”</button></div><p>Lock Screen Preview</p><div className="lock-preview"><b>09:41</b><span>Thursday, 12 March</span><article><Icon name="lock" /><span><strong>System Update</strong><small>You have a new update</small></span></article></div></Screen> }
function Pin() { const [currentPin, setCurrentPin] = useState(''); const [newPin, setNewPin] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState(''); const update = (setter: (value: string) => void) => (event: React.ChangeEvent<HTMLInputElement>) => setter(event.target.value.replace(/\D/g, '').slice(0, 4)); const submit = async () => { if (newPin !== confirmation) { setMessage('The new PINs do not match.'); return } try { await accountVault.changePin(currentPin, newPin); setMessage('Your PIN has been changed.'); setCurrentPin(''); setNewPin(''); setConfirmation('') } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Could not change PIN') } }; return <Screen title="Change PIN"><main className="pin-main"><h2>Change your PIN</h2><p>Changing your PIN does not change your account identity.</p><label>Current PIN<input type="password" inputMode="numeric" autoComplete="current-password" value={currentPin} onChange={update(setCurrentPin)} /></label><label>New 4-digit PIN<input type="password" inputMode="numeric" autoComplete="new-password" value={newPin} onChange={update(setNewPin)} /></label><label>Confirm new PIN<input type="password" inputMode="numeric" autoComplete="new-password" value={confirmation} onChange={update(setConfirmation)} /></label>{message && <p role="status">{message}</p>}<button className="settings-primary" disabled={currentPin.length !== 4 || newPin.length !== 4 || confirmation.length !== 4} onClick={submit}>Change PIN</button></main></Screen> }
function AccountId() { const [copied, setCopied] = useState(false); const [publicKey, setPublicKey] = useState(''); useEffect(() => { void accountVault.summary().then((summary) => setPublicKey(summary?.publicKey || '')) }, []); const copy = async () => { if (!publicKey) return; await navigator.clipboard?.writeText(publicKey); setCopied(true) }; const short = publicKey ? `${publicKey.slice(0, 8)}…${publicKey.slice(-4)}` : 'Loading…'; return <Screen title="Your account ID"><main className="account-id"><section><strong>{short}</strong><span className="qr-placeholder">▦</span><button onClick={copy} disabled={!publicKey}><Icon name="copy" />{copied ? 'Copied' : 'Copy ID to Clipboard'}</button></section><p>Share this only if a counselor asks to confirm it’s you. It can’t be used to get into your account.</p><aside><Icon name="warn" />Your backup words are different. Never share those with anyone.</aside></main></Screen> }
function Backup() { return <Screen title="Back up your account"><main className="backup-intro"><p><Icon name="phone" />If you lose this phone or clear the app, your backup words are the only way back into your account.</p><p><Icon name="lock" />We can’t recover your account for you.</p><p><Icon name="warn" />No counselor, organisation or person from this app will ever ask for your backup words.</p><button className="settings-primary" onClick={() => go('/app/settings/backup/words')}><Icon name="eye" />Show my backup words</button><button className="text-button" onClick={() => go('/app/settings')}>Remind me later</button></main></Screen> }
function BackupWords() {
  const [shown, setShown] = useState(false)
  const [pin, setPin] = useState('')
  const [words, setWords] = useState<string[]>([])
  const [error, setError] = useState('')
  const [exportStatus, setExportStatus] = useState('')
  const reveal = async () => {
    try {
      setWords((await accountVault.revealBackupWords(pin)).split(' '))
      setPin('')
      setError('')
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Could not unlock backup words')
    }
  }
  const copy = async () => {
    try {
      if (!navigator.clipboard?.writeText) throw new Error('Clipboard access is unavailable')
      await navigator.clipboard.writeText(backupPhrase(words))
      setExportStatus('Backup words copied. Clear your clipboard after storing them safely.')
    } catch {
      setExportStatus('Could not copy. Your browser may have blocked clipboard access.')
    }
  }
  const download = () => {
    const url = URL.createObjectURL(
      new Blob([backupDownloadText(words)], { type: 'text/plain;charset=utf-8' }),
    )
    const link = document.createElement('a')
    link.href = url
    link.download = 'resilience-backup-words.txt'
    link.click()
    window.setTimeout(() => URL.revokeObjectURL(url), 0)
    setExportStatus('Backup file downloaded. Move it somewhere private and delete extra copies.')
  }
  return <Screen title="Your backup words"><main className="backup-words">{words.length === 0 ? <><label>Enter your PIN<input type="password" inputMode="numeric" autoComplete="current-password" value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, '').slice(0, 4))} /></label>{error && <p role="alert">{error}</p>}<button className="settings-primary" disabled={pin.length !== 4} onClick={reveal}><Icon name="eye" />Unlock backup words</button></> : <><div className={!shown ? 'blurred' : ''}>{words.map((word, index) => <span key={`${word}-${index}`}><b>{index + 1}</b>{word}</span>)}</div><button onPointerDown={() => setShown(true)} onPointerUp={() => setShown(false)} onPointerCancel={() => setShown(false)} onPointerLeave={() => setShown(false)}><Icon name="eye" />Hold to reveal</button><aside><Icon name="warn" />Anyone with these words can access your account. Copies and downloaded files may remain on this device or in cloud backups.</aside><section className="backup-export-actions" aria-label="Backup word export options"><button className="settings-secondary" onClick={copy}><Icon name="copy" />Copy words</button><button className="settings-secondary" onClick={download}><Icon name="download" />Download</button></section>{exportStatus && <p className="backup-export-status" role="status">{exportStatus}</p>}<button className="settings-primary" onClick={() => go('/app/settings/backup/check')}><Icon name="check" />I’ve stored them safely</button></>}</main></Screen>
}
function BackupCheck() { const [pin, setPin] = useState(''); const [options, setOptions] = useState<string[]>([]); const [correctWord, setCorrectWord] = useState(''); const [choice, setChoice] = useState(''); const [error, setError] = useState(''); const prepare = async () => { try { const words = (await accountVault.revealBackupWords(pin)).split(' '); setCorrectWord(words[2]); setOptions([words[0], words[2], words[4], words[6], words[8], words[10]].sort(() => Math.random() - 0.5)); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not check backup words') } }; const correct = choice !== '' && choice === correctWord; const done = async () => { await accountVault.confirmBackup(); localStorage.setItem('account-backed-up', 'true'); go('/app/settings') }; return <Screen title="Check your backup"><main className="backup-check"><h2>Tap word #3 in your backup words to confirm you wrote it down.</h2>{options.length === 0 ? <><label>Enter your PIN<input type="password" inputMode="numeric" autoComplete="current-password" value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, '').slice(0, 4))} /></label>{error && <p role="alert">{error}</p>}<button className="settings-primary" disabled={pin.length !== 4} onClick={prepare}>Continue</button></> : <><div>{options.map((word) => <button className={choice === word ? 'selected' : ''} onClick={() => setChoice(word)} key={word}>{word}</button>)}</div>{choice && <p className={correct ? 'success' : 'error'}>{correct ? <><Icon name="check" />Your account is backed up</> : 'That’s not word #3. Try again.'}</p>}<button className="settings-primary" disabled={!correct} onClick={done}>Done</button></>}</main></Screen> }
function AccountSafety() { return <Screen title="Account safety"><main className="safety-main"><h2>Let’s make your account safe again</h2><article><b>1</b><h3>Change your PIN now</h3><button className="settings-primary" onClick={() => go('/app/settings/pin')}>Change PIN</button></article><article><b>2</b><h3>Start a new account</h3><p>Your circle and conversations won’t move over. Let your counselor know your new account ID.</p><button className="settings-secondary" onClick={() => window.location.assign('/onboarding/create')}>Start a new account</button></article><article><b>3</b><h3>Tell your counselor</h3><button className="settings-primary" onClick={() => window.location.assign('/app/counselors')}>Message a counselor</button></article><aside>Messages you’ve already sent can’t be taken back.</aside><a href="tel:1195">☎ In danger right now? Call 1195 (free)</a></main></Screen> }
function ClearPhone() { const timer = useRef<number | null>(null); const [holding, setHolding] = useState(false); const stop = () => { if (timer.current) window.clearTimeout(timer.current); timer.current = null; setHolding(false) }; const start = () => { setHolding(true); timer.current = window.setTimeout(() => { void clearPrivateDeviceData().then(() => window.location.replace('/onboarding/safety')) }, 3000) }; return <Screen title="Clear this phone"><main className="clear-main"><h2><Icon name="warn" />Clear everything from this phone</h2><h3>This will delete from this phone:</h3><ul><li>your messages and conversations</li><li>your circle contacts</li><li>saved resources & records</li><li>wallet history & balance</li><li>your account credentials on this device</li></ul><h3>This won’t delete:</h3><ul><li>Messages other people have received</li><li>Copies kept by the services that deliver messages</li></ul><aside>This can’t be undone. If you haven’t backed up, you won’t be able to get back into this account.<br /><button onClick={() => go('/app/settings/backup')}>Back up first</button></aside><button className={`clear-hold ${holding ? 'holding' : ''}`} onPointerDown={start} onPointerUp={stop} onPointerLeave={stop} onPointerCancel={stop}><strong>Clear everything</strong><small>Hold for 3 seconds</small></button><button className="settings-secondary" onClick={() => history.back()}>Cancel</button></main></Screen> }

export default function Settings() { const path = window.location.pathname; if (path.endsWith('/notifications')) return <Notifications />; if (path.endsWith('/timer')) return <Timer />; if (path.endsWith('/pin')) return <Pin />; if (path.endsWith('/account-id')) return <AccountId />; if (path.endsWith('/backup/words')) return <BackupWords />; if (path.endsWith('/backup/check')) return <BackupCheck />; if (path.endsWith('/backup')) return <Backup />; if (path.endsWith('/account-safety')) return <AccountSafety />; if (path.endsWith('/privacy')) return <Privacy />; if (path.endsWith('/clear')) return <ClearPhone />; return <SettingsHome /> }
