# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nauthz.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "nauthz.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cnauthz.proto\x12\x06nauthz"\xa5\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x0e\n\x06pubkey\x18\x02 \x01(\x0c\x12\x12\n\ncreated_at\x18\x03 \x01(\x06\x12\x0c\n\x04kind\x18\x04 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12$\n\x04tags\x18\x06 \x03(\x0b\x32\x16.nauthz.Event.TagEntry\x12\x0b\n\x03sig\x18\x07 \x01(\x0c\x1a\x1a\n\x08TagEntry\x12\x0e\n\x06values\x18\x01 \x03(\t"\xaa\x02\n\x0c\x45ventRequest\x12\x1c\n\x05\x65vent\x18\x01 \x01(\x0b\x32\r.nauthz.Event\x12\x14\n\x07ip_addr\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06origin\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nuser_agent\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x61uth_pubkey\x18\x05 \x01(\x0cH\x03\x88\x01\x01\x12\x32\n\x05nip05\x18\x06 \x01(\x0b\x32\x1e.nauthz.EventRequest.Nip05NameH\x04\x88\x01\x01\x1a*\n\tNip05Name\x12\r\n\x05local\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\tB\n\n\x08_ip_addrB\t\n\x07_originB\r\n\x0b_user_agentB\x0e\n\x0c_auth_pubkeyB\x08\n\x06_nip05"R\n\nEventReply\x12"\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x10.nauthz.Decision\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message*L\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44\x45\x43ISION_PERMIT\x10\x01\x12\x11\n\rDECISION_DENY\x10\x02\x32I\n\rAuthorization\x12\x38\n\nEventAdmit\x12\x14.nauthz.EventRequest\x1a\x12.nauthz.EventReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "nauthz_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DECISION"]._serialized_start = 577
    _globals["_DECISION"]._serialized_end = 653
    _globals["_EVENT"]._serialized_start = 25
    _globals["_EVENT"]._serialized_end = 190
    _globals["_EVENT_TAGENTRY"]._serialized_start = 164
    _globals["_EVENT_TAGENTRY"]._serialized_end = 190
    _globals["_EVENTREQUEST"]._serialized_start = 193
    _globals["_EVENTREQUEST"]._serialized_end = 491
    _globals["_EVENTREQUEST_NIP05NAME"]._serialized_start = 385
    _globals["_EVENTREQUEST_NIP05NAME"]._serialized_end = 427
    _globals["_EVENTREPLY"]._serialized_start = 493
    _globals["_EVENTREPLY"]._serialized_end = 575
    _globals["_AUTHORIZATION"]._serialized_start = 655
    _globals["_AUTHORIZATION"]._serialized_end = 728
# @@protoc_insertion_point(module_scope)
