"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 18:28:05.315898
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("nostr_pubkey", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("nip05_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("per_payment_cap_sat", sa.Integer(), server_default="0", nullable=False),
        sa.Column("daily_cap_sat", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('pending', 'approved', 'suspended')", name="ck_org_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
        sa.UniqueConstraint("nostr_pubkey"),
    )
    op.create_table(
        "seen_auth_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column(
            "seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_seen_auth_events_seen_at"), "seen_auth_events", ["seen_at"], unique=False
    )
    op.create_table(
        "disbursements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("amount_sat", sa.Integer(), nullable=False),
        sa.Column("amount_kes", sa.Integer(), nullable=False),
        sa.Column("rate_source", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="CREATED", nullable=False),
        sa.Column("payment_hash", sa.String(length=64), nullable=True),
        sa.Column("invoice", sa.Text(), nullable=True),
        sa.Column("invoice_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_pubkey", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "reason_code IN ('transport', 'pharmacy', 'shelter', 'food', 'other')",
            name="ck_disbursement_reason",
        ),
        sa.CheckConstraint(
            "state IN ('CREATED', 'INVOICE_ATTACHED', 'PAYING', 'PAID', 'EXPIRED', 'FAILED', 'CANCELLED')",
            name="ck_disbursement_state",
        ),
        sa.CheckConstraint("amount_sat > 0", name="ck_disbursement_amount_positive"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "idempotency_key", name="uq_disbursement_idempotency"),
        sa.UniqueConstraint("payment_hash"),
    )
    op.create_table(
        "roster_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "counsellor_attestations",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("counsellor_pubkey", sa.String(length=64), nullable=False),
        sa.Column("roster_event_id", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["roster_event_id"],
            ["roster_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("org_id", "counsellor_pubkey"),
    )
    op.create_table(
        "disbursement_transitions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("disbursement_id", sa.UUID(), nullable=False),
        sa.Column("from_state", sa.Text(), nullable=True),
        sa.Column("to_state", sa.Text(), nullable=False),
        sa.Column("actor_pubkey", sa.String(length=64), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["disbursement_id"], ["disbursements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disbursement_transitions")
    op.drop_table("counsellor_attestations")
    op.drop_table("roster_events")
    op.drop_table("disbursements")
    op.drop_index(op.f("ix_seen_auth_events_seen_at"), table_name="seen_auth_events")
    op.drop_table("seen_auth_events")
    op.drop_table("organizations")
    # ### end Alembic commands ###
